---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: automation-home-assistant
  # namespace: media
spec:
  path: ./home-assistant/home-assistant/base
  sourceRef:
    kind: GitRepository
    name: home-assistant
    namespace: flux-system
  interval: 2m
  prune: true
  wait: true
  dependsOn:
    - name: longhorn-system-longhorn
      namespace: flux-system
    - name: traefik-traefik
      namespace: flux-system
    # - name: automation-home-assistant-config
    #   namespace: flux-system