---
# yaml-language-server: $schema=https://raw.githubusercontent.com/SchemaStore/schemastore/master/src/schemas/json/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: automation
resources:
  - ./storage.yaml
  # - ./hacs-config.yaml
  - ./deployment.yaml
  - ./service.yaml
  - ./ingressroute.yaml
configMapGenerator:
  - name: home-assistant-config
    files:
      - configuration.yaml
      - automations.yaml
      - scripts.yaml
      - scenes.yaml
generatorOptions:
  disableNameSuffixHash: true