---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: homeassistant-cluster
spec:
  description: "PostgreSQL Home Assistant DB"
  imageName: ghcr.io/cloudnative-pg/postgresql:16.4
  instances: 2
  bootstrap:
    initdb:
      database: homeassistant_db
      owner: ${SECRET_HOMEASSISTANT_PG_USER}
      secret:
        name: homeassistant-cnpg-user-secret
  storage:
    storageClass: longhorn
    size: 10Gi
  resources:
    requests:
      memory: 500Mi
      cpu: 300m
    limits:
      memory: 1Gi
      cpu: 1
  monitoring:
    enablePodMonitor: true
