apiVersion: v1
kind: Secret
metadata:
    name: homeassistant-cnpg-user-secret
    annotations:
        replicator.v1.mittwald.de/replicate-to: monitoring-system,cnpg-system
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:bgO3aZ4ponMHi5tD4cSW2GUt+bLbKFQ8iohrXUjsow==,iv:dlw0a+R9HVl0/Pjgt3zGsnzfrrwlqmwxiBAKTFHoD68=,tag:friqOXmsVFZLGZxvUgBPuA==,type:str]
    password: ENC[AES256_GCM,data:9dO6s3qkbI4vnPLCunsrlyOvSdZaduLCqgV0rK0eyUGKTAc=,iv:O41GOIWvMDNmQts0HJ2lDTkT/KOIRSga2IZDs3u7/Xw=,tag:oSLXvo1Q0q6UoP9zmS+c3A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age109fzapgarv59gpyu5tgmwgn7j3hwmfs0dhrz3lrqvjy046jxafnse30kvj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlS0V3NVBGSXJLVkRHWFpp
            cHpBT1RDSWo2QlZvK2ZWN0NTSnUwVUZzZlRNClFqTDlselZWZXdGMWlTN3RnUlZt
            VTl6bjRlZlhmOXdCTnhPS3FBSUZhY3cKLS0tIHZVYWhWcEx1ZjBkTGVWSUFFZ0sz
            ei9LOW9sdkdTbTJkZVZQeHdtdG5rUTQKnbwl8rVJiu531j1NbEEML9r0hf6rxb0f
            zc62f3nKVMlIRE9IEl4/G83xjhJnOA5ncx4l91bNh/a96JkyNm/UcA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-18T09:19:27Z"
    mac: ENC[AES256_GCM,data:llBzrSw4brUG2i9GZbYyZYJgkusCHRqdBSzOU6kmHmQsSVsw7dLTiCB/vsvHuVDX4kXtnQmVfUxUGe1L+mBo/D3OXWY7ITyP7SeSJ5TCVI47xerhJEVAu5sP+21wrFJQMEAkVZ8BExK2CdSBaK3YsRnoquKC2j3PzN1tWAdPNeE=,iv:K5u4qV+k/M/ObnYCkXgMH8tD8cLY+lU4KAZFfSlgidY=,tag:rwqreZe92V2n6tTHEmJpmA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|caBundle)$
    version: 3.9.2
