apiVersion: v1
kind: Secret
metadata:
    name: homeassistant-cnpg-user-secret
    annotations:
        replicator.v1.mittwald.de/replicate-to: monitoring-system,cnpg-system
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:bgO3aZ4ponMHi5tD4cSW2GUt+bLbKFQ8iohrXUjsow==,iv:dlw0a+R9HVl0/Pjgt3zGsnzfrrwlqmwxiBAKTFHoD68=,tag:friqOXmsVFZLGZxvUgBPuA==,type:str]
    password: ENC[AES256_GCM,data:9dO6s3qkbI4vnPLCunsrlyOvSdZaduLCqgV0rK0eyUGKTAc=,iv:O41GOIWvMDNmQts0HJ2lDTkT/KOIRSga2IZDs3u7/Xw=,tag:oSLXvo1Q0q6UoP9zmS+c3A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age109fzapgarv59gpyu5tgmwgn7j3hwmfs0dhrz3lrqvjy046jxafnse30kvj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlS0V3NVBGSXJLVkRHWFpp
            cHpBT1RDSWo2QlZvK2ZWN0NTSnUwVUZzZlRNClFqTDlselZWZXdGMWlTN3RnUlZt
            VTl6bjRlZlhmOXdCTnhPS3FBSUZhY3cKLS0tIHZVYWhWcEx1ZjBkTGVWSUFFZ0sz
            ei9LOW9sdkdTbTJkZVZQeHdtdG5rUTQKnbwl8rVJiu531j1NbEEML9r0hf6rxb0f
            zc62f3nKVMlIRE9IEl4/G83xjhJnOA5ncx4l91bNh/a96JkyNm/UcA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-17T12:59:50Z"
    mac: ENC[AES256_GCM,data:YL5fmcV6JUO5d7EJsxzOP5tjGR01h6eCVNF+fNwzwm0G9WwHvdAUMJaGZqZaLjfI/AM4/eI45Ft3rXD9VQL0Zs/QrHUK5rdX0jGe6O+Ny83RyhtjJvBLZf6KOaeZdjsNEqwp4X3WEtk6864MuxOyyM6p3Eolki4NHhF41REvos0=,iv:fBww5as2shATwEW80CnV0cCEO++RDuWLhkYtbN7icXc=,tag:fA6aFPptaoTHZ9Wjj5C/Og==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|caBundle)$
    version: 3.9.2
